###Send Request
http://localhost:4004/odata/v4/catalog

###
http://localhost:4004/odata/v4/catalog/EmployeService

###
http://localhost:4004/odata/v4/catalog/ProductService

###
POST http://localhost:4004/odata/v4/catalog/EmployeService
Content-Type: application/json


    {
      "ID": "02BD2137-0890-1EEA-A6C2-BB55C19788CC",
      "accountnumber": "777888999",
      "bankId": "510000111",
      "bankName": "My Bank of santhu",
      "currency_code": "USD",
      "email": "kl.rahul@itelo.info",
      "gender": "M",
      "language": "E",
      "loginName": "KLRAHUL",
      "nameFirst": "K L",
      "nameIntials": null,
      "namelast": "Rahul",
      "nameMiddle": null,
      "PhoneNumber": "+1 999 374 524",
      "salary": "55500.00"
    }
###
GET http://localhost:4004/odata/v4/catalog/EmployeService/02BD2137-0890-1EEA-A6C2-BB55C19788CC


###
PATCH http://localhost:4004/odata/v4/catalog/EmployeService/02BD2137-0890-1EEA-A6C2-BB55C19788CC
Content-Type: application/json

{
    "gender": "F",
     "salary": "750000"
}

###
DELETE http://localhost:4004/odata/v4/catalog/EmployeService/02BD2137-0890-1EEA-A6C2-BB55C19788CC

###
GET http://localhost:4004/odata/v4/catalog/PurchaseOrderS?$expand=Items

###
GET http://localhost:4004/odata/v4/catalog/getEmployeeInfo()

###
GET http://localhost:4004/odata/v4/catalog/PurchaseOrderS('74867AD200E41EDBA5D8B0C98DC28052')/largetOrder()
###
POST http://localhost:4004/odata/v4/catalog/PurchaseOrderS/74867AD200E41EDBA5D8B0C98DC28052/discountPrice